on: [push]


env:
 GITHUB_ACTION_PATH: lol
 
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: th3vi33z/hello-world-composite-action@main
        with:
          who-to-greet: 'Vicky!' 
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: ls -la /home/runner/work/_actions/nic3c-usr/hello-world-composite-action/main
        shell: bash
      
