on: 
  push:
  workflow_dispatch:
  
env: 
  TEST_SEC: ${{secrets.TEST_SEC}}
 
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello.
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: th3vi33z/hello-world-composite-action@main
        with:
          who-to-greet: 'Vicky!' 
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: echo -n $TEST_SEC | od -A n -t x1  
        shell: bash
 
      
