on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: nic3c-usr/hello-world-composite-action@main
        with:
          who-to-greet: 'Vicky'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: printenv | grep -i github
        shell: bash
