on: [push]


env:
 GITHUB_ACTION_PATH: lol
 
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: foo
        uses: ./th3vi33z/hello-world-composite-action
        with:
          who-to-greet: 'Vicky!' 
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
 
      
