on: 
  push:
  workflow_dispatch:
  
env:
  TEST_SEC: ${{secrets.TEST}}

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello.
    steps:
      - id: foo
        uses: th3vi33z/hello-world-composite-action@main
        with:
          who-to-greet: 'Vicky!' 
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
 
      
